
name: Prevent Streamlit Sleep
on:
  schedule:
    - cron: '0 */10 * * *' # Automatically runs every 10 hours
  workflow_dispatch:      # Lets you click a button to run it manually

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App URL
        run: |
          curl -s https://jizehlnj8zf7gmk8tjavwq.streamlit.app/ > /dev/null
